name: Check Commit Message
on: push

concurrency: commit-msg-${{ github.sha }}

jobs:
  check-commit-msg:
    runs-on: ubuntu-latest
    env:
      # The Python version your project uses. Feel free to change this if required.
      PYTHON_VERSION: "3.10"

    steps:
      # Checks out the repository in the current folder.
      - name: Checks out repository
        uses: actions/checkout@v3

      # Set up the right version of Python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check for Valid commit message
        run: |
          python -m pip install pre-commit
          python -m pip freeze --local
          echo ${{ github.event.commits[0].message }} >> /tmp/msg
          pre-commit run --hook-stage commit-msg --commit-msg-filename /tmp/msg check-commit-msg
